import {
  type ContainerNode,
  createActionRow,
  createButton,
  createContainer,
  createSection,
  createSeparator,
  createTextDisplay,
} from "@/lib/document";
import { SITE_NAME, SITE_TAGLINE, SITE_URL } from "@/lib/site";

/**
 * The tool's own component embed, built with the tool's own model so the page
 * Discord unfurls is a demonstration of what the builder produces.
 */
export const selfEmbed = (): ContainerNode => {
  const headline = createSection();
  headline.components = [
    createTextDisplay(
      `# [${SITE_NAME}](${SITE_URL})\n${SITE_TAGLINE}`,
    ),
  ];
  headline.accessory = {
    ...createButton(),
    label: "Open builder",
    url: SITE_URL,
  };

  const links = createActionRow();
  links.components = [
    { ...createButton(), label: "Open builder", url: SITE_URL },
  ];

  return createContainer([
    headline,
    createTextDisplay(
      "- Tree, inspector and a client-accurate preview\n- Every limit checked before you copy\n- HTML, JSON, Next.js, Astro and SvelteKit output",
    ),
    createSeparator(),
    createTextDisplay(
      "-# This preview is itself a component embed, generated by the builder.",
    ),
    links,
  ]);
};
